INSERT INTO txstatebookfinder.auth_permission (id, name, content_type_id, codename) VALUES (1, 'Can add log entry', 1, 'add_logentry');
INSERT INTO txstatebookfinder.auth_permission (id, name, content_type_id, codename) VALUES (2, 'Can change log entry', 1, 'change_logentry');
INSERT INTO txstatebookfinder.auth_permission (id, name, content_type_id, codename) VALUES (3, 'Can delete log entry', 1, 'delete_logentry');
INSERT INTO txstatebookfinder.auth_permission (id, name, content_type_id, codename) VALUES (4, 'Can add permission', 2, 'add_permission');
INSERT INTO txstatebookfinder.auth_permission (id, name, content_type_id, codename) VALUES (5, 'Can change permission', 2, 'change_permission');
INSERT INTO txstatebookfinder.auth_permission (id, name, content_type_id, codename) VALUES (6, 'Can delete permission', 2, 'delete_permission');
INSERT INTO txstatebookfinder.auth_permission (id, name, content_type_id, codename) VALUES (7, 'Can add group', 3, 'add_group');
INSERT INTO txstatebookfinder.auth_permission (id, name, content_type_id, codename) VALUES (8, 'Can change group', 3, 'change_group');
INSERT INTO txstatebookfinder.auth_permission (id, name, content_type_id, codename) VALUES (9, 'Can delete group', 3, 'delete_group');
INSERT INTO txstatebookfinder.auth_permission (id, name, content_type_id, codename) VALUES (10, 'Can add content type', 4, 'add_contenttype');
INSERT INTO txstatebookfinder.auth_permission (id, name, content_type_id, codename) VALUES (11, 'Can change content type', 4, 'change_contenttype');
INSERT INTO txstatebookfinder.auth_permission (id, name, content_type_id, codename) VALUES (12, 'Can delete content type', 4, 'delete_contenttype');
INSERT INTO txstatebookfinder.auth_permission (id, name, content_type_id, codename) VALUES (13, 'Can add session', 5, 'add_session');
INSERT INTO txstatebookfinder.auth_permission (id, name, content_type_id, codename) VALUES (14, 'Can change session', 5, 'change_session');
INSERT INTO txstatebookfinder.auth_permission (id, name, content_type_id, codename) VALUES (15, 'Can delete session', 5, 'delete_session');
INSERT INTO txstatebookfinder.auth_permission (id, name, content_type_id, codename) VALUES (16, 'Can add user', 6, 'add_user');
INSERT INTO txstatebookfinder.auth_permission (id, name, content_type_id, codename) VALUES (17, 'Can change user', 6, 'change_user');
INSERT INTO txstatebookfinder.auth_permission (id, name, content_type_id, codename) VALUES (18, 'Can delete user', 6, 'delete_user');
INSERT INTO txstatebookfinder.auth_permission (id, name, content_type_id, codename) VALUES (19, 'Can add courses', 7, 'add_courses');
INSERT INTO txstatebookfinder.auth_permission (id, name, content_type_id, codename) VALUES (20, 'Can change courses', 7, 'change_courses');
INSERT INTO txstatebookfinder.auth_permission (id, name, content_type_id, codename) VALUES (21, 'Can delete courses', 7, 'delete_courses');
INSERT INTO txstatebookfinder.auth_permission (id, name, content_type_id, codename) VALUES (22, 'Can add professor detail', 8, 'add_professordetail');
INSERT INTO txstatebookfinder.auth_permission (id, name, content_type_id, codename) VALUES (23, 'Can change professor detail', 8, 'change_professordetail');
INSERT INTO txstatebookfinder.auth_permission (id, name, content_type_id, codename) VALUES (24, 'Can delete professor detail', 8, 'delete_professordetail');
INSERT INTO txstatebookfinder.auth_permission (id, name, content_type_id, codename) VALUES (25, 'Can add shopping cart', 9, 'add_shoppingcart');
INSERT INTO txstatebookfinder.auth_permission (id, name, content_type_id, codename) VALUES (26, 'Can change shopping cart', 9, 'change_shoppingcart');
INSERT INTO txstatebookfinder.auth_permission (id, name, content_type_id, codename) VALUES (27, 'Can delete shopping cart', 9, 'delete_shoppingcart');
INSERT INTO txstatebookfinder.auth_permission (id, name, content_type_id, codename) VALUES (28, 'Can add book detail', 10, 'add_bookdetail');
INSERT INTO txstatebookfinder.auth_permission (id, name, content_type_id, codename) VALUES (29, 'Can change book detail', 10, 'change_bookdetail');
INSERT INTO txstatebookfinder.auth_permission (id, name, content_type_id, codename) VALUES (30, 'Can delete book detail', 10, 'delete_bookdetail');
INSERT INTO txstatebookfinder.auth_permission (id, name, content_type_id, codename) VALUES (31, 'Can add credit card details', 11, 'add_creditcarddetails');
INSERT INTO txstatebookfinder.auth_permission (id, name, content_type_id, codename) VALUES (32, 'Can change credit card details', 11, 'change_creditcarddetails');
INSERT INTO txstatebookfinder.auth_permission (id, name, content_type_id, codename) VALUES (33, 'Can delete credit card details', 11, 'delete_creditcarddetails');
INSERT INTO txstatebookfinder.auth_permission (id, name, content_type_id, codename) VALUES (34, 'Can add customer', 12, 'add_customer');
INSERT INTO txstatebookfinder.auth_permission (id, name, content_type_id, codename) VALUES (35, 'Can change customer', 12, 'change_customer');
INSERT INTO txstatebookfinder.auth_permission (id, name, content_type_id, codename) VALUES (36, 'Can delete customer', 12, 'delete_customer');
INSERT INTO txstatebookfinder.auth_permission (id, name, content_type_id, codename) VALUES (37, 'Can add book details', 10, 'add_bookdetails');
INSERT INTO txstatebookfinder.auth_permission (id, name, content_type_id, codename) VALUES (38, 'Can change book details', 10, 'change_bookdetails');
INSERT INTO txstatebookfinder.auth_permission (id, name, content_type_id, codename) VALUES (39, 'Can delete book details', 10, 'delete_bookdetails');